### ISSUE TITLE
Export: Add ability to export data from a node-value datatype

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3060]
Add ability to export a node-value datatype to csv and json. 

#### Acceptance Criteria
- [x] Ability to export a node-value datatype to csv
- [x] Ability to export a node-value datatype to json
- [x] Unit Tests passed
- [ ] Documentation

**Comment by ryan86** [comment]
To export:

json: use regular json export command

csv: use regular csv export command but as format(-f) put `tilecsv`

**Comment by apeters** [comment]
both .csv and .json tested and exported successfully
