### ISSUE TITLE
Create tree view of graph for left panel

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3201]
I propose a few changes from the current way that graphs are built up.

For new Resource Graphs:
- [x] Currently, only branches can be added to the root node.  A single node branch should be able to be added.
- [x] A single node should be able to be added anywhere in the graph (just like you can with branches).  In this case it seems like just adding a single node is sufficient, no need to bring up the branch list.

For new Branches:
- [x] Currently users are allowed to select a branch to add to the current branch.  I suggest that this could be greatly simplified by only allowing single nodes to be added to a branch.  There would then be no need to show the branch list.

General suggestions:
- [x] I recommend we remove the node/nodetype built-in branch.
- [x] I recommend that we hard code into the system then idea of a single node. Right now a single node is treated like any branch and because of this could be deleted accidentally, with no way to get it back.
- [ ] We should make node names unique to a graph.  <-- maybe we don't really need to do this anymore

When clicking on the plus button from the root node the branch list should be expanded

![Screen Shot 2018-04-03 at 3.39.01 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/1eaeef55-49ae-444e-9839-25ee78253beb)

**Comment by dwuthrich** [comment]
Note that jsTree (https://www.jstree.com/) provides interactive trees, it supports HTML & JSON data sources, AJAX & async callback loading.

**Comment by apeters** [comment]
We already use jqtree https://mbraak.github.io/jqTree/ with the RDM which supports all our current use cases, so we would probably stick with that.

**Comment by chiatt** [comment]
Meets requirements.

**Comment by apeters** [comment]
For posterity I'm copying this discussion from a Slack conversation about enforcing unique node names in a graph.

```
@here I’d like to implement our restriction on node names to make them unique to a graph, but
 most of our data repos (DISCO, Lincoln) have duplicate node names.
Lincoln especially seems to have quite a few.  I don’t know if that’s something easily 
changed at the moment.

Here’s a list of duplicate nodes in the Lincoln graphs

apeters [12:54 PM]
uploaded and commented on this image: Screen Shot 2018-05-03 at 12.50.16 PM.png 
Duplicate nodes in Lincoln graphs

robgaston [12:54 PM]
perhaps this is something we can/should handle w/ a migration
I assume we would need to for users w/ existing projects in production

azaroth42 [12:54 PM]
This is the label for the node in a branch?

robgaston [12:54 PM]
and we could then use that migration to upgrade our packages
@azaroth42 effectively its  a uniqueness constraint on two columns in the 
`nodes` table: `name` & `graphid`
so that a given graph can only have a single node w/ a given name

azaroth42 [12:56 PM]
A given model?

robgaston [12:56 PM]
yes
resource model or branch

adamlodge [12:57 PM]
that has some implications to the workflow for importing branches into resource models - 
especially in cases where the branch is (for example) an ARM-blessed branch.  In those 
cases, we cant presuppose a target resource model.

apeters [12:58 PM]
I suppose I could run a migration that would append a `_{number}` to any duplicate node name, 
alternatively, if the migration of a users instance failed because of duplicate names, the users 
themselves could update the nodes manually, which they would probably want to do anyway, 
and then run the migration (edited)

robgaston [1:00 PM]
it would make upgrading easy & then you could go back and fix node names as needed

azaroth42 [1:00 PM]
We have a lot of duplicate names in our models too, but it could be easily reconciled. I think 
@adamlodge’s observation is the important one, of importing branches into models that 
would create a duplicate

apeters [1:02 PM]
When appending a branch we’d have to de-duplicate node names as well

adamlodge [1:03 PM]
i suppose the `_{number}` approach there would work fine. (edited)
what do you think @azaroth42?

azaroth42 [1:05 PM]
I don't see a problem ... but (apologies) could we discuss the benefits we expect to realize 
from the constraint?
If it's to be able to reference that particular node within the model with a human friendly 
name rather than the UUID, and you write code against that in the /branch/ ... you then 
have a problem when it gets renamed upstream in the model

apeters [1:08 PM]
I think we were thinking of that basic use case.  Allow a user to use a friendly name to 
look up a node value.
But maybe that’s just not compelling enough.
```

**Screen Shot 2018-05-03 at 12.50.16 PM.png :**
Duplicate nodes in Lincoln graphs
![screen shot 2018-05-03 at 12 50 16 pm](https://user-images.githubusercontent.com/823773/40560962-626d772c-6010-11e8-8e35-bfcddbc9784a.png)
