### ISSUE TITLE
4.1.1 testing script

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3279]
1st [x] == Chrome; 2nd [x] == Safari; 3rd [x] == Firefox, 4th [x] == Internet Explorer 11

**Mobile Survey Manager**
- [x] [x] [x] [x] Test that users can't access the Mobile Survey Manager page

**Auth** 
- [x] [x] [x] [x] User can sign themselves up for a new Arches account
- [x] [x] [x] [x] User is added to default group (Crowdsource Editor)
- [x] [x] [x] [x] User can log in with their email address
- [x] [x] [x] [x] User can change their password
- [x] [x] [x] [x] User can edit their profile (First and Last name, email address, etc...)

**Search** - Alexei
- [x] [x] [x] [x] Free text search
- [x] [x] [x] [x] Concept search
- [x] [x] [x] [x] Map search 
- [x] [x] [x] [x] Time range based search
- [x] [x] [x] [x] Time wheel search
- [x] [x] [x] [x] Advanced search
- [x] [x] [x] [ ] Related resource search
   - [x] [x] [x] [x] Paging
   - [x] [x] [x] [ ] D3 graph

**Related Resources** See Ticket #3352
- Resource Editor
- [x] [x] [x] [x] User can add a related resource
- [x] [x] [x] [ ] User can delete a related resource
- [x] [x] [x] [x] User can change the properties of related resources
- [x] [x] [x] [ ] User can switch between table and force directed graph
- [x] [x] [x] [x] User can page through related resources in table

- Search
- [x] [x] [x] [ ] Hovering over a link in the force directed graph opens a panel with source and target node info and list each unique relationship type
- [x] [x] [x] [ ] Hovering over a node highlights the adjacent links and the corresponding entry in the node list
- [x] [x] [x] [ ] Hovering over a node list entry highlights the corresponding node and its adjacent links 
- [x] [x] [x] [ ] User can switch between table and force directed graph
- [x] [x] [x] [x] Entering text in the search field filters the list of list entries
-  Users can create custom map popups
   - 

**Map Widget**
- [x] [x] [x] [x] Point line and poly geoms can be created, edited, and deleted 
- [x] [x] [x] [x] XY widget is working properly
- [x] [ ] [x] [.5] Valid geojson entered in the geojson input adds features to the map and pans to those features. If geojson is invalid user has a chance to update data. See tickets #3368 and #3369

**Map Layer Manager** -- INTERNET EXPLORER See tickets #3349 and #3350
- Resource Layers
   - [x] [x] [x] [x] Settings - changes to the name and icon of a layer are reflected in the map widget overlay list and overlay library
   - [x] [x] [x] [x] Deactivating/Activating a resource layer hides/shows the layer in the map widget overlay list and overlay library
   - [x] [x] [x] [x] Style Settings - changes to the layer style are displayed in the layer
   - [x] [x] [x] [x] Style Settings Advanced - changes to the layer style are displayed in the layer
   - [x] [x] [x] [x] Clustering
      - [x] [x] [x] [x] Increasing cluster distance causes features to cluster at increased distances between them
      - [x] [x] [x] [x] Increasing cluster max zoom causes clusters to be formed at higher zoom levels 
      - [x] [x] [x] [x] Decreasing min points to 2 points causes clusters to form with only 2 points
      - [x] [x] [x] [x] Increasing vector simplification to 0.0 prevents simplification a low zoom levels
    - [x] [x] [x] [x] Activating caching adds a cache folder for a resource in your projects tileserver directory
    - [x] [x] [x] [x] Activating clean cache on edit updates the cache when a geometry is edited
    - [x] [x] [x] [x] Setting permissions for a user or group as No Access removes the user and group from the permissions list under the permissions tab.
    
- Basemaps
    - [x] [x] [x] [x] Changing the default search basemap in the basemap settings is reflected on the search page
    - [x] [x] [x] [x] Settings - changes to the name and icon of a layer are reflected in the map widget basemap list
    - [x] [x] [x] [x] User can delete a basemap and it no longer appears in the map widget's list of basemaps
    
- Overlays
    - [x] [x] [x] [x] Settings - changes to the name and icon of a layer are reflected in the map widget overlay list and overlay library
    - [x] [x] [x] [x] User can delete an overlay and it no longer appears in the map widget overlay library

**RDM**
- **Thesauri**
   - [x] [x] [x] [x] Add scheme
   - [x] [x] [x] [x] Delete scheme
   - [x] [x] [x] [x] Import scheme
   - [x] [x] [x] [x] Export scheme
   - [x] [x] [x] [x] Add top concept
   - [x] [x] [x] [x] Import from SPARQL
   - [x] [x] [x] [x] Manage parents
   - [x] [x] [x] [x] Make collection
   - [x] [x] [x] [x] Add label
   - [x] [x] [x] [x] Add Note
   - [x] [x] [x] [x] Add image

- **Collections**
   - [x] [x] [x] [x] Add collection
   - [x] [x] [x] [x] Delete collection
   - [x] [x] [x] [x] Export all collections
   - [x] [x] [x] [x] Add dropdown entry
   - [x] [x] [x] [x] Add sort order and confirm in dropdown

**Import/Export** - Alexei
- [x] [x] [x] [x] Create_mapping_file
- [x] [x] [x] [x] Import business data
- [x] [x] [x] [x] Export business data
- [x] [x] [x] [x] Load package
- [x] [x] [x] [x] Create package

**Graph/Resource Designer**
- [x] [x] [x] [x] Export graph
- [x] [x] [x] [x] Import graph
- [x] [x] [x] [x] Create branch
- [x] [x] [x] [x] Create resource
- [x] [x] [x] [x] Add/Edit cards 
- [x] [x] [x] [x] Add/Edit menus
- [x] [x] [x] [x] Add/Edit reports
- [x] [x] [x] [x] delete graph -- can delete different nodes and node groups, but not an entire graph
- [x] [x] [x] [x] clone graph

**Resource Instance Management** 
- Confirm edits for all data types
   - [x] [x] [x] [x] String
   - [x] [x] [x] [x] Concepts
   - [x] [x] [x] [x] Domains
   - [x] [ ] [x] [x] Images
   - [x] [x] [x] [x] Dates
   - [x] [x] [x] [x] Number
   - [x] [x] [x] [x] Boolean
   - [x] [x] [x] [x] GeoJson
   - [x] [x] [x] [x] Resource instance type
   - [ ] [ ] [ ] [ ] Node data type :exclamation:
   - [ ] [ ] [ ] [ ] IIIF
   - [ ] [ ] [ ] [ ] Chart type
- Updating of a resource descriptor should be reflected in:
   - [x] [x] [x] [x] search results
   - [x] [x] [x] [x] form headings
   - [x] [x] [x] [x] report headings
   - [x] [x] [x] [x] map popups
   - [x] [x] [x] [ ] related resource d3 graph and listings - only shows up for source resource node not related nodes -- IE11 see ticket #3352

**System Settings**
- [ ] [ ] [ ] [ ] Project Name - Updating name updates in index.htm and the page tab--- SEE TICKET #3339
- [ ] [ ] [ ] [ ] Web Analytics - String value insterts in base.htm at the location of this template variable:{{GOOGLE_ANALYTICS_TRACKING_ID}}
- Confirm map settings ---- See ticket #3349 and #3350
    - [x] [x] [x] [ ] API Key - Key saves and API calls are successful
    - [x] [x] [x] [ ] Hex Grid Precision - Saves properly, but errors if precision is too high (`Exception detail: TransportError(400, u'parsing_exception', u'[geohash_grid] failed to parse field [precision]')`)
    - [x] [x] [x] [ ] Hex Cell Size - Changes reflected in Search results
    - [x] [x] [x] [x] Default Zoom - Changes reflected in Card Config Manager
    - [x] [x] [x] [x] Min Zoom - Changes reflected in Card Config Manager
    - [x] [x] [x] [x] Max Zoom - Changes reflected in Card Config Manager
    - [x] [x] [x] [x] Project Extent - Changes reflected in Card Config Manager

- Confirm search settings
    - Basic Search Settings
        - [x] [x] [x] [x] Searches per page updates properly in Search
        - [x] [x] [x] [x] Number of search suggestions is reflected in search term input
    - Temporal Search Settings (Not currently used)
        - [ ] Changes in time wheel color ramp are reflected in time wheel change time wheel colors (not in use)
        - [ ] Changes in time wheel config are reflected in time wheel (not in use)
    - Saved Searches
        - [x] [x] [x] [ x] A new search saves with a name, search url, description, and image and displays properly in the saved search page. -- Image Does not get put into the saved searchs 
        - [x] [x] [x] [x] Users can delete a saved search

**Permissions Management** - Alexei
   - [x] [x] [x] [x] Confirm removing `read` permissions removes that section from the report
   - [x] [x] [x] [x] Confirm removing `read` permissions removes that section from the form
   - [x] [x] [x] [x] Confirm removing `read` permissions removes that section from the adv. search
   - [x] [x] [x] [x] Confirm removing `read` permissions for a spatial nodegroup removes that resource type from map based search results
   - [x] [x] [x] [x] Confirm removing `read` permissions for a spatial nodegroup removes that resource type from the overlays section of the map settings 
   - [x] [x] [x] [x] Confirm removing `read` permissions for a spatial nodegroup removes the map from the Map Report
   - [x] [x] [x] [x] Confirm removing `read` permissions for a date based nodegroup removes the related entries from the type dropdown in the time filer of the search page
   - [x] [x] [x] [x] Confirm removing `read` permissions for a date based nodegroup reduces the wheel count appropriately
   - [x] [x] [x] [x] Confirm removing `write` permissions but still having `read` permissions disallows saving that section of the form

**Reports** - Alexei
   - [x] [x] [x] [x] Confirm that report templates with map header gets rendered correctly
   - [x] [x] [x] [x] Confirm that report templates with image header gets rendered correctly
   - [x] [x] [x] [x] Confirm that report templates with no header gets rendered correctly
   - Confirm tile data rendered properly for each data type
      - [x] [x] [x] [x] String
      - [x] [x] [x] [x] Concepts
      - [x] [x] [x] [x] Domains
      - [x] [x] [x] [x] Images
      - [x] [x] [x] [x] Dates
      - [x] [x] [x] [x] Number
      - [x] [x] [x] [x] Boolean
      - [x] [x] [x] [x] GeoJson
      - [x] [x] [x] [x] Resource instance type
      - [ ] [ ] [ ] [ ] IIIF
      - [ ] [ ] [ ] [ ] Chart type

**Install** 
- [x] Confirm that upgrading from previous release (4.1.0) is issue free :exclamation:

**Comment by apeters** [comment]
4.1.1 tagged and released
