### ISSUE TITLE
Add form and report widgets for each data type

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#339]
need to be created to support each data type used in forms .
eg:
- [x] Text input (string)
- [x] Toggle switch (boolean)
- [x] Calendar (date)
- [x] Textarea (string)
- [x] Number (numerics)
- [x] Radio-boolean (boolean)
- [x] Concept-dropdown (single-select)
- [x] Concept-dropdown (multi-select)
- [x] Concept-radio (single-select)
- [x] Concept-checkbox (multi-select)
- [x] Map (geometry)
- [x] File upload (file)
- [x] Image upload (image)
- [ ] Resource list

**Comment by dwuthrich** [comment]
meets requirements
