### ISSUE TITLE
Create API endpoint to GET a single concept

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3399]
GET `/rdm/concepts/{concept_id}`
- Return single object representing the concept
- Add custom header value (eg: X-Arches-IncludeChildren) to inform system to return child concept references

output formats supported:
- json (our current format)

**Comment by jmunowitch** [comment]
Steps to test this:

1. Register a client at `http://localhost:8000/o/applications/` to receive the client ID.
2. Client Type: public. Authorization Grant Type: password
3. Follow steps at https://arches.readthedocs.io/en/latest/api/#auth: `curl -X POST http://localhost:8000/o/token/ -d "username=admin&password=admin&grant_type=password&client_id=<client id>"` to receive token
5. get json concept: `curl -H "Authorization: Bearer <client id> " -X GET http://localhost:8000/rdm/concepts/<UUID>?f=json`

A few example UUIDs for Concepts that may be available based upon the installed package:
- Activity Type: `eaf99308-095e-424d-ac8b-51d1da78deb4`
- Recommendation Type: `49eac741-7640-4fe5-8ac0-e5659b4f9129` 

Things to test: 
- [ ] Concept is returned if exists
- [ ] Only RDM Admin have access
- [ ] 404 response is returned when no concept exists (View this in the Arches Logs)
- [ ] Returns json and json-ld correctly

**Comment by jmunowitch** [comment]
json-ld capability moved into a new ticket: #3562

**Comment by apeters** [comment]
This didn't work for me until I removed this line:
`@method_decorator(group_required('RDM Administrator'), name='dispatch')`

I think we need to check if the user is part of the RDM Amin group from within the get method like I did with the resource PUT request when I use `user_can_edit_resources`

**Comment by apeters** [comment]
We don't want to be using `@method_decorators` at all.
The problem with using decorators is that they don't allow us to catch the error and return an appropriate response status (like http 403).
See how I use `user_can_edit_resources` in the PUT request for resources as an example.

**Comment by apeters** [comment]
meets requirements
