### ISSUE TITLE
Improve searching/filtering of trees in the graph designer, resource editor, card manager, etc..

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3551]
<s>When filtering/searching for nodes in a tree remove any node from the tree that doesn't match the search/filter leaving any non-matching parents of a child that matches the search/filter.</s>

We should add a couple functional enhancements to these trees:
- [ ] expand tree as needed to expose any hits when filter changes
- [ ] add a key listener for return on the filter text box to auto-scroll the tree to the next hit

This should be applied to the following components:
 - [ ] graph designer
 - [ ] new card manger
 - [ ] resource editor (searching should include tile data displayed in the tree)

**Comment by dwuthrich** [comment]
meets requirements
