### ISSUE TITLE
Allow users to delete a model, even if it has instances associated with it

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3574]
Allow users to delete a model, even if it has instances associated with it 

 - [ ] Make sure to show an alert that warns the user that they will lose data.
- [ ] Because this could be a long running process, you might need to prevent users from saving instances associated with this graph before deleting those instances.
- [ ] Create a command line script to do the same (look at the script that can remove all resources, there may be some overlap there)

**Comment by adamlodge** [comment]
Likely some overlap here with issue #3257.

**Comment by apeters** [comment]
I deleted a graph with about 2000 records and noticed several things:
1. The data was deleted, but the graph wasn't (returned a 500 error)
2. I was still able to add a new instance of the resource type while the delete was occurring.
3. The command wasn't documented (or rather the flag "graph" wasn't documented)

<img width="688" alt="screen shot 2018-07-03 at 3 32 44 pm" src="https://user-images.githubusercontent.com/823773/42247622-70e0d21a-7ed6-11e8-8444-65ed1870beef.png">
