### ISSUE TITLE
Stub out UI sections for "Functions" and "Reports" in the card manager

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3649]
We just need empty placeholders for these 3 sections of the UI:
- [x] Middle tabbed panel with tabs for "Functions" and "Reports"
- [ ] Content panel for "Functions"
- [ ] Content panel for "Reports"

Required functionality:
- [ ] User clicks on root card in card manager to show middle panel with "Functions" tab active and "Functions" content panel displayed
- [ ] Clicking on "Reports" tab displays "Report" preview panel

![Screen Shot 2018-07-05 at 10.27.11 AM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/ee8e8b61-41c6-4d23-ab76-167cf7a99c5b)

**Comment by chiatt** [comment]
Closing because this ticket addresses issues in the deprecated UI.
