### ISSUE TITLE
Add "New" button to Graph Manager UI

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3738]
Currently, there is no way to define a new branch or resource model from the Graph Manager without first returning to the Arches Designer Page.

Add a "Manage..." button to the top panel of the Graph Manager similar to the resource editor.  Include a "New Branch" and "New Model" entry in the manage list.  

Also, include a delete function for the current model/branch (see #3734)

**Comment by jmunowitch** [comment]
Additional Functions to be added:

- [ ] Clone Current `Resource Model` || `Branch`
- [ ] Export Current `Resource Model` || `Branch`
- [ ] Import `Resource Model` or `Branch`
- [ ] Delete Associated Instances

**Comment by jmunowitch** [comment]
@dwuthrich: The Menu is done, but I am having trouble deciding on an order for all these new options. Do you have a preference?

<img width="395" alt="screen shot 2018-08-22 at 23 01 44" src="https://user-images.githubusercontent.com/1542229/44507443-70d65a00-a65f-11e8-9cbb-bfca09bdfea1.png">

**Comment by ryan86** [comment]
meets requirements.
