### ISSUE TITLE
The settings page for a Branch should be updated to reflect the differences between it and the resource settings

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3804]
We can probably remove the following items:
- [x] Resource models that may be related
- [x] Color

Root Node:
- [x] Allow users to set the data type of the root node to something other than 'semantic'.
- [x] "Make Card" switch should also always be on and disabled (or hidden) for the root node of a branch.

**Comment by jmunowitch** [comment]
@apeters: Is the implication here that a root node in a branch should be treated as a non-root node would be in a Resource model?

Would we add the additional UI below the standard graph settings areas?

**Comment by apeters** [comment]
@jmunowitch the root node in a branch starts a new card(nodegroup), whereas in a resource model it does not.

**Comment by chiatt** [comment]
It looks like there is a connection between setting the datatype of a branch's root node and the dirty state of cards #3787. I'm going to assign myself this ticket take a look until I get #3787 figured out.

**Comment by apeters** [comment]
@jmunowitch I would move the contents of the section entitled "Root Node Data Type and Settings" to the section "Configuration".

Also, "JSON-LD Context" doesn't make sense in the context of a branch.  It should be removed.

**Comment by apeters** [comment]
meets requirements
