### ISSUE TITLE
Sync instance data between Couch and Postgres

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#4161]
Users are able to sync data between the device and couch, but updating postgres with the changes to tile records in Couch remains to done. Each tile revision from couch should be saved as a provisional edit in its respective tile.

**Comment by apeters** [comment]
I created this a while back.  I don't know if it will be of help, but here it is in any case.

![syncworkflow](https://user-images.githubusercontent.com/823773/47115082-5e693e80-d212-11e8-8a71-02a9a504af09.jpg)

**Comment by jmunowitch** [comment]
Initial sync implementation in place. Edits made in Mobile are imported as Provisional in Postgres. 

Need to add a bit more logic in here:
- [ ] Do not overwrite completed changes to the tile that happened outside of the Mobile Workflow (Only Write provisional edits from the specific user)
- [ ] Confirm that any conflicts in CouchDB have been accounted for (Multiple Couch Users editing the same instance)
- [ ] If the User is a Resource Reviewer, edits should not be provisional (they should be authoritative).

Questions:
- During the Couch -> PostgreSQL process, should PostgreSQL -> Couch be initiated? 
-

**Comment by chiatt** [comment]
Working as expected.
