### ISSUE TITLE
As a graph designer I want to configure and save the data entry card container, cards, and widget settings associated with my graph so that a Resource Designer can use my graph and data entry forms

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#524]
## Acceptance Criteria
- [x] I can toggle between the graph design and card manager to see how my design decisions impact the data entry forms
- [x] I can define labels, widgets, cardinality, and help files for the card container and cards (e.g.: node groups) implied by my graph design
- [x] I can save these settings so that they are the defaults when some one adds my graph to a resource
## Definition of Done

A user can open my graph and inspect the graph design and the settings I saved for the data entry card container, cards, and widgets in my graph

**Comment by dwuthrich** [comment]
meets requirements
