### ISSUE TITLE
Valid Graph Patterns and Structures

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#573]
The point of this Epic is to start a discussion around what a Graph is and what a Resource is and their similarities and differences.

Some semantics first:
a graph (little g) is a hierarchical list of nodes and edges. Both Resources and Graphs are graphs.  A Resource is composed of Graphs.

A Resource:
 - Has a root node that is never grouped.
 - Can have appended directly below the root, copies of Graph instances
 - Can only append Graphs that are rooted with a grouping node
 - Cannot append a Graph as the child of another Graph

A Graph:
 - Has a root node that is by default a grouping node.  If it's not a grouping node, then it has to be the only node in the graph.
 - Can only nest child node groups 1 deep
 - Can have any number of nodes within the root group that are semantic
 - Can have any number of nodes within the root group that are non-semantic, but then the Graph can't contain any other node groups other than the root node group

UI impacts:
- [x] 'make card' switch:
    - hidden for resource root node
    - disabled if node is not a collector and node group has a parent node group
    - disabled if node is not a collector and node group includes nodes (current node & downstream nodes excepted) w/ datatype other than 'semantic'
    - disabled for graph root if graph has more than one node
    - disabled if node is a collector and is in a node group with non-semantic nodes that is a child or parent nodegroup
    - should be labeled 'Make sub-card' for nodes that are downstream of the card root
- [x] 'datatype' drop down:
    - disabled for all nodes in a parent nodegroup
    - disabled (or hidden entirely) for resource root node
- [x] filter the branch list:
    - exclude graphs that would create an invalid graph
    - exclude graphs that don't have a root node group when working on a resource
- [x] disable appending of branches on any node other than the root when working on a resource

**Comment by apeters** [comment]
the requirement above

> disable appending of branches on any node other than the root when working on a resource

is effectively taken care of by logic in the "canAppend" method in graph.js
