### ISSUE TITLE
Localization Final Check

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#8344]
Check the following closed tickets for regressions and completeness:
- [ ] String datatype https://github.com/archesproject/arches/issues/6458
- [ ] String widget https://github.com/archesproject/arches/issues/7794
- [ ] Number widget https://github.com/archesproject/arches/issues/7800
- [ ] Boolean widget https://github.com/archesproject/arches/issues/7801
- [ ] Resource instance widget https://github.com/archesproject/arches/issues/7802
- [ ] Resource Instance list widget https://github.com/archesproject/arches/issues/7803
- [ ] Domain widget https://github.com/archesproject/arches/issues/7804
- [ ] Domain list widget https://github.com/archesproject/arches/issues/7805
- [ ] Node value widget https://github.com/archesproject/arches/issues/7806
- [ ] EDTF widget https://github.com/archesproject/arches/issues/7807
- [ ] Concept widget https://github.com/archesproject/arches/issues/7808
- [ ] Concept and concept-list widget https://github.com/archesproject/arches/issues/7809
- [ ] Date widget https://github.com/archesproject/arches/issues/7811
- [ ] Map widget https://github.com/archesproject/arches/issues/7812
- [ ] Concept value https://github.com/archesproject/arches/issues/6679
- [ ] URL widget https://github.com/archesproject/arches/issues/7810
- [ ] Card labels https://github.com/archesproject/arches/issues/7798
- [ ] Widget name https://github.com/archesproject/arches/issues/7892
- [ ] PO file generation widget https://github.com/archesproject/arches/issues/7845
- [ ] Update from PO file https://github.com/archesproject/arches/issues/7846
- [ ] Localized search https://github.com/archesproject/arches/issues/7890
- [ ] Graph export https://github.com/archesproject/arches/issues/7980
- [ ] Graph import https://github.com/archesproject/arches/issues/7981
- [ ] Graph name and subtitle https://github.com/archesproject/arches/issues/7899
- [ ] Primary descriptors https://github.com/archesproject/arches/issues/8157
- [ ] CSV export https://github.com/archesproject/arches/issues/8154
- [ ] CSV import
- [ ] Arches file import
- [ ] Arches file export
- [ ] JSON-LD file export
- [ ] JSON-LD file import

- [ ] Confirm all pages style properly in RTL
- [ ] Confirm side navigation works as expected
